# Generated by Django 6.0.3 on 2026-03-27 05:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='アニメ名')),
                ('image_url', models.URLField(blank=True, verbose_name='画像URL')),
                ('score', models.DecimalField(blank=True, decimal_places=1, help_text='0.0〜100.0（未評価は空欄）', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))], verbose_name='点数')),
                ('year', models.IntegerField(verbose_name='放送年度')),
                ('season', models.CharField(choices=[('春', '春'), ('夏', '夏'), ('秋', '秋'), ('冬', '冬')], max_length=1, verbose_name='放送シーズン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'アニメ',
                'verbose_name_plural': 'アニメ',
                'ordering': ['-score', '-year', 'season', 'title'],
            },
        ),
    ]
